language: go
go: 
 - 1.8.x
 - 1.9.x
install:
 - go get -v 
 - go get -v github.com/fatih/color
 - go get -v github.com/olekukonko/tablewriter
 - go get -u github.com/alecthomas/gometalinter
script:
 - gometalinter --install
 - gometalinter --config=./gometalinter.json --vendor ./...
